# Generated by Django 4.2.3 on 2023-07-07 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenderapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bidder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idNo', models.CharField(max_length=255)),
                ('orgName', models.CharField(max_length=255)),
                ('orgCategory', models.CharField(choices=[('Private', 'Private'), ('Public', 'Public'), ('Government', 'Government')], max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenderReg',
            fields=[
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('tenderid', models.CharField(blank=True, max_length=255, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('clinteId', models.CharField(blank=True, max_length=255, null=True)),
                ('deadLineDate', models.DateField()),
                ('procure_method', models.CharField(max_length=255)),
                ('financial_value', models.CharField(max_length=255)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenderapp.category')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='user',
        ),
        migrations.DeleteModel(
            name='JobPosition',
        ),
        migrations.AlterField(
            model_name='cvdocument',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenderapp.bidder'),
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
