# Generated by Django 4.2.3 on 2023-07-07 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenderapp', '0002_bidder_category_tenderreg_remove_student_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidderReg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=255)),
                ('tinNo', models.CharField(max_length=255)),
                ('companyRegNo', models.CharField(max_length=255)),
                ('vatNo', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('region', models.CharField(choices=[('Arusha', 'Arusha'), ('Dar es Salaam', 'Dar es Salaam'), ('Dodoma', 'Dodoma'), ('Geita', 'Geita'), ('Iringa', 'Iringa')], max_length=255)),
                ('district', models.CharField(blank=True, choices=[('Arusha', [('Arusha City', 'Arusha City'), ('Arusha District', 'Arusha District')]), ('Dar es Salaam', [('Ilala', 'Ilala'), ('Kinondoni', 'Kinondoni')])], max_length=255, null=True)),
                ('phone', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('website', models.CharField(max_length=255)),
                ('business', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('foreignInput', models.CharField(max_length=255)),
                ('employeeNum', models.CharField(max_length=255)),
                ('passwords', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='bidapplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('time_to_complete', models.PositiveIntegerField(blank=True, null=True)),
                ('bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bidder.bidderreg')),
                ('tender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tenderapp.tenderreg')),
            ],
        ),
    ]
