# Generated by Django 4.2.3 on 2023-07-10 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bidder', '0003_selectedbidder'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bidderreg',
            name='user',
        ),
    ]
